default: &default
  adapter: postgresql
  encoding: unicode
  username: juliaaa
  password: 1234
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ftptools

test:
  <<: *default
  database: ftptools_test

